export enum TokenType {
  Undefined = "Undefined",
  Identifier = "Identifier",
  Keyword = "Keyword",
  Assign = "Assign",
  Number = "Number",
  EndOfLine = "EndOfLine",
  EndOfFile = "EndOfFile",
  Punctuation = "Punctuation",

  // Operators
  Operator = "Operator",
  Multiply = "Multiply",
  Power = "Power",
  MultiplyBy = "MultiplyBy",
  Divide = "Divide",
  DivideBy = "DivideBy",
  Comment = "Comment",
  IsEqual = "IsEqual",
  IsNotEqual = "IsNotEqual",
  LessEqual = "LessEqual",
  GreaterEqual = "GreaterEqual",
  Not = "Not",
  Less = "Less",
  Greater = "Greater",
  Minus = "Minus",
  MinusBy = "MinusBy",
  Decrement = "Decrement",
  Plus = "Plus",
  PlusBy = "PlusBy",
  Increment = "Increment",
  OpenParenthesis = "OpenParenthesis",
  CloseParenthesis = "CloseParenthesis",
  Or = "Or",
  And = "And",
  Boolean = "Boolean",
}
